# NOTE: The actions below will be executed in the order of definition
repos:
    # Remove unused imports
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: [ "--in-place", "--remove-all-unused-imports" ]
    # Format imports
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
    # Format code
  - repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: ["-pri", "src"]
